name: "EDX Github Action"
description: "EDX Github Action"
inputs:
  config-path:
    description: "Config path"
    required: true
    default: "./lighthouserc.js"
runs:
  using: "composite"
  steps:
    - name: Install GSA EDX Lighthouse plugin
      run: npm install https://github.com/GSA/lighthouse-plugin-edx#main
      shell: bash
    - name: Audit site with Lighthouse
      id: lighthouse_audit
      uses: treosh/lighthouse-ci-action@v10
      with:
        configPath: ${{ inputs.config-path }}
        uploadArtifacts: false
        temporaryPublicStorage: true
    - name: Format Lighthouse score
      id: format_lighthouse_score
      uses: actions/github-script@v3
      with:
        script: |
          const result = ${{ steps.lighthouse_audit.outputs.manifest }}[0].summary
          const links = ${{ steps.lighthouse_audit.outputs.links }}

          const formatResult = (res) => Math.round((res * 100))
          Object.keys(result).forEach(key => result[key] = formatResult(result[key]))

          const score = res => res >= 90 ? '🟢' : res >= 50 ? '🟠' : '🔴'

          const comment = [
              `⚡️ [Lighthouse report](${Object.values(links)[0]}) for the changes in this PR:`,
              '| Category | Score |',
              '| --- | --- |',
              `| ${score(result.performance)} Performance | ${result.performance} |`,
              `| ${score(result.accessibility)} Accessibility | ${result.accessibility} |`,
              `| ${score(result['best-practices'])} Best practices | ${result['best-practices']} |`,
              `| ${score(result.seo)} SEO | ${result.seo} |`,
              `| ${score(result.pwa)} GSA EDX | ${result['lighthouse-plugin-edx']} |`
          ].join('\n')

            core.setOutput("comment", comment);
    - name: Add comment to PR
      id: comment_to_pr
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          ${{ steps.format_lighthouse_score.outputs.comment }}
